version: "3.8"

services:
  web:
    build: ./src
    ports:
        - "8080:8080"
    volumes:
        - "$PWD/src:/src"
  neo4j:
      image: "neo4j:latest"
      ports:
        - "7474:7474"
        - "7687:7687"
      environment:
          - "NEO4J_AUTH=none"
  mongo:
      image: "mongo"
      ports:
        - "27017:27017"
