version: "3.8"

services:
  backend:
    build: ./src
    ports:
        - "8082:8082"
    volumes:
        - "$PWD/src:/src"
  frontend:
    build: ./front
    ports:
        - "8081:3000"
    volumes:
        - "$PWD/front:/app"
  neo4j:
      image: "neo4j:latest"
      ports:
        - "7474:7474"
        - "7687:7687"
      environment:
          - "NEO4J_AUTH=none"
  mongo:
      image: "mongo"
      ports:
        - "27017:27017"
