version: "3.8"

services:
  backend:
    build: ./src
    ports:
        - "4444:8080"
    volumes:
        - "$PWD/src:/src"
    links:
        - neo4j
        - mongo
    depends_on:
        - neo4j
        - mongo
  frontend:
    build: ./front
    ports:
        - "8081:3000"
    volumes:
        - "$PWD/front:/app"
    links:
        - backend
  neo4j:
      image: "neo4j:latest"
      ports:
        - "7474:7474"
        - "7687:7687"
      environment:
          - "NEO4J_AUTH=none"
  mongo:
      image: "mongo"
      ports:
        - "27017:27017"
